name: BF Website CI

on:
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - run: npm ci
      - run: npm run check
      - run: npm run generate:sitemap
      - run: npm test
      - run: npm run build
